// AUTO-GENERATED by .claude/skills/bridgebuilder-review/scripts/gen-bb-registry.ts
// DO NOT EDIT. Regenerate with `npm run gen-bb-registry` (or `bun run gen-bb-registry`).
// Source: .claude/defaults/model-config.yaml
//
// Per-provider defaults applied at codegen time (yaml tracks API context_window
// only; maxOutput + coefficient are BB-skill truncation heuristics):
//   anthropic / bedrock / google: maxOutput=8192, coefficient=0.25
//   openai:                       maxOutput=4096, coefficient=0.23
//   default fallback:             maxInput=100000, maxOutput=4096, coefficient=0.25
//
// maxInput = effective_input_ceiling − 20000 when the yaml entry carries the
// v3 ceiling (cycle-124 FR-3 / SDD §2.1: BB truncates below cheval's pre-flight
// gate instead of dispatching what exit 7 would reject), else context_window.
//
// cycle-099 sprint-1 (T1.1). See SDD §1.4.3 + §5.3.

import type { TokenBudget } from "./types.js";

export const GENERATED_TOKEN_BUDGETS: Record<string, TokenBudget> = {
  "claude-fable-5": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-fable-5-1": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-haiku-4-5-20251001": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-headless": { maxInput: 1000000, maxOutput: 8192, coefficient: 0.25 },
  "claude-opus-4-6": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-opus-4-7": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-opus-4-8": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-opus-5": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-sonnet-4-5-20250929": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-sonnet-4-6": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "claude-sonnet-5": { maxInput: 160000, maxOutput: 8192, coefficient: 0.25 },
  "us.anthropic.claude-haiku-4-5-20251001-v1:0": { maxInput: 200000, maxOutput: 8192, coefficient: 0.25 },
  "us.anthropic.claude-opus-4-7": { maxInput: 200000, maxOutput: 8192, coefficient: 0.25 },
  "us.anthropic.claude-opus-4-8": { maxInput: 200000, maxOutput: 8192, coefficient: 0.25 },
  "us.anthropic.claude-sonnet-4-6": { maxInput: 200000, maxOutput: 8192, coefficient: 0.25 },
  "composer-2.5": { maxInput: 200000, maxOutput: 4096, coefficient: 0.25 },
  "composer-2.5-fast": { maxInput: 200000, maxOutput: 4096, coefficient: 0.25 },
  "deep-research-pro": { maxInput: 1048576, maxOutput: 8192, coefficient: 0.25 },
  "gemini-2.0-flash": { maxInput: 1048576, maxOutput: 8192, coefficient: 0.25 },
  "gemini-2.5-flash": { maxInput: 1048576, maxOutput: 8192, coefficient: 0.25 },
  "gemini-2.5-pro": { maxInput: 1048576, maxOutput: 8192, coefficient: 0.25 },
  "gemini-3-flash-preview": { maxInput: 1048576, maxOutput: 8192, coefficient: 0.25 },
  "gemini-3.1-pro-preview": { maxInput: 1048576, maxOutput: 8192, coefficient: 0.25 },
  "gemini-headless": { maxInput: 1048576, maxOutput: 8192, coefficient: 0.25 },
  "codex-headless": { maxInput: 400000, maxOutput: 4096, coefficient: 0.23 },
  "gpt-5.2": { maxInput: 128000, maxOutput: 4096, coefficient: 0.23 },
  "gpt-5.3-codex": { maxInput: 400000, maxOutput: 4096, coefficient: 0.23 },
  "gpt-5.5": { maxInput: 400000, maxOutput: 4096, coefficient: 0.23 },
  "gpt-5.5-pro": { maxInput: 400000, maxOutput: 4096, coefficient: 0.23 },
  "grok-build": { maxInput: 256000, maxOutput: 4096, coefficient: 0.25 },
  "grok-composer-2.5-fast": { maxInput: 256000, maxOutput: 4096, coefficient: 0.25 },
  "default": { maxInput: 100000, maxOutput: 4096, coefficient: 0.25 },
};
