<!--
  /structure — THE MEMBRANE.

  The epistemic structure of the lab, made legible. Not the spine (that's WHEN
  beliefs settle); this is the axis underneath it: a belief is GENERATED by a
  nondeterministic source (it can be wrong undetectably), and only counts once a
  DETERMINISTIC instrument settles it (same input → same answer → no room to
  hallucinate). The membrane is the gate between the two.

  Register: freeside (taste.md). Bone data · phosphor HELD · anomaly FALSIFIED ·
  cyan structural chrome · void silence. No radii, no smooth easing, mono only.
  Every value on this page is grounded in a committed artifact (SETTLE-001).
-->
<script lang="ts">
  // The generators — nondeterministic SENSORS. They PROPOSE a BELIEF.
  const generators = ['HUMAN', 'AGENT', 'LLM'];
  // The ladder — the epistemic TIER a BELIEF holds before it crosses.
  // Canonical tiers: SPECULATION → CLAIMED → READY → (SETTLED, past the gate).
  const ladder = [
    { rung: 'SPECULATION', note: 'no grounding · a guess', tone: 'ghost' },
    { rung: 'CLAIMED', note: 'cited by a SENSOR · checkable, not settled', tone: 'dim' },
    { rung: 'READY', note: 'a pre-registered BAR exists · worth the cost to settle', tone: 'base' }
  ];
  // The INSTRUMENTS — deterministic settlers. They SETTLE (never resolve/verify/judge).
  const instruments = ['HASH', 'TEST', 'ON-CHAIN', 'MARKET P&L'];
  // The verdicts. INSUFFICIENT = ran, couldn't decide (≠ PENDING = not run).
  const verdicts = [
    { v: 'HELD', cls: 'held', note: 'reproduced · survives' },
    { v: 'FALSIFIED', cls: 'falsified', note: 'the kill · a first-class outcome' },
    { v: 'INSUFFICIENT', cls: 'insufficient', note: 'ran · couldn’t decide' }
  ];
</script>

<svelte:head><title>structure · the membrane</title></svelte:head>

<main>
  <header class="head">
    <p class="kicker">AGENTIC-ECONOMY // EPISTEMIC STRUCTURE</p>
    <h1>THE MEMBRANE</h1>
    <p class="thesis">
      A belief counts for nothing until something that <em>cannot hallucinate</em> settles it.
      The lab generates with the nondeterministic — and only scores the deterministic.
    </p>
  </header>

  <!-- ── the membrane ── -->
  <section class="panel">
    <div class="panel-inner membrane">
      <!-- LEFT: nondeterministic -->
      <div class="field field-gen">
        <p class="field-label">NONDETERMINISTIC · GENERATES</p>
        <p class="field-sub">can be wrong undetectably</p>
        <div class="chips">
          {#each generators as g}<span class="chip chip-gen">{g}</span>{/each}
        </div>
        <div class="ladder">
          {#each ladder as l}
            <div class="rung rung-{l.tone}">
              <span class="rung-name">{l.rung}</span>
              <span class="rung-note">{l.note}</span>
            </div>
          {/each}
        </div>
      </div>

      <!-- MIDDLE: the gate ──────────────────────────────────────────────
           KANSEI / YANAGI motion (feel-and-apply 2026-06-13). The gate is the
           membrane a belief must CROSS to count. The motion TEACHES the
           crossing, in-register (STEPS ONLY — taste.md forbids smooth easing):

           1. THE CROSSING. A belief token steps left→right across the membrane
              in 8 discrete jumps (steps(8) over --duration-deliberate = 800ms =
              8 perceptual cycles). It does not GLIDE — the membrane is a
              checkpoint, not a slope. It enters bone-ghost (a proposed,
              unsettled belief) and lands phosphor at the right edge (the
              measured, SETTLED signal). The color carries the meaning.
           2. THE LINE. The membrane glow pulses on a slow steps(4) cycle —
              the checkpoint, breathing.
           3. THE INSTRUMENTS. The four settlers boot line-by-line on entry
              (beam-draw, 83ms quantum stagger) — the gate powers up.

           prefers-reduced-motion zeroes every duration via tokens.css; the
           token then rests phosphor at the right edge (settled), no traversal. -->
      <div class="gate">
        <div class="gate-line" aria-hidden="true"></div>
        <p class="gate-label">SETTLEMENT<br />INSTRUMENT</p>
        <p class="gate-sub">same input<br />→ same answer</p>

        <!-- the crossing lane — a belief stepping the membrane -->
        <div class="crossing" aria-hidden="true">
          <span class="crossing-rail"></span>
          <span class="crossing-token"></span>
        </div>

        <div class="gate-instruments">
          {#each instruments as i, idx}<span class="instr" style="--instr-i: {idx}">{i}</span>{/each}
        </div>
        <p class="gate-rule">never an LLM</p>
      </div>

      <!-- RIGHT: deterministic -->
      <div class="field field-det">
        <p class="field-label">DETERMINISTIC · SETTLES</p>
        <p class="field-sub">reproducible · scoped · scored</p>
        <div class="verdicts">
          {#each verdicts as vd}
            <div class="verdict v-{vd.cls}">
              <span class="v-name">{vd.v}</span>
              <span class="v-note">{vd.note}</span>
            </div>
          {/each}
        </div>
      </div>
    </div>
  </section>

  <!-- ── the worked example: SETTLE-001 crossing the membrane ── -->
  <section class="panel">
    <p class="panel-cap">SETTLE-001 · one belief, crossing</p>
    <div class="panel-inner example">
      <div class="ex ex-gen">
        <p class="ex-tier">AI claim · unverified</p>
        <p class="ex-belief">“x402 agentic-payment volume is mostly wash-trading.”</p>
        <p class="ex-meta">Claim sensor: Gemini, open-source web research. 41 of 50 citations had their sources fact-checked · cost surfaced first · $0 (subscription).</p>
        <p class="ex-source">~81% figure sourced from Artemis Analytics + Allium Labs.</p>
        <p class="ex-stamp">claimed ~81% wash</p>
      </div>
      <div class="ex-arrow">
        <span class="ex-arrow-glyph" aria-hidden="true">→</span>
        <span class="ex-arrow-lbl">DUNE · ON-CHAIN</span>
        <a class="ex-query" href="https://dune.com/queries/7717781" target="_blank" rel="noopener">query 7717781 ↗</a>
        <span class="ex-arrow-cost">cost to settle: 0.075 credits</span>
      </div>
      <div class="ex ex-det">
        <p class="ex-tier ex-held">HELD · deterministic</p>
        <p class="ex-belief ex-result">99.3% is the same address paying itself.</p>
        <p class="ex-meta">$18,287 of $18,408 over 30d · genuine ≈ $121 · scope: the x402x payment router.</p>
        <p class="ex-source">Source: Dune on-chain query, re-runnable above.</p>
        <p class="ex-stamp ex-held-stamp">the map said 81% · the territory said 99%</p>
      </div>
    </div>
  </section>

  <!-- ── the refinement: is the breakdown right? — tucked (a second read) ── -->
  <details class="panel notes-panel">
    <summary class="notes-summary">
      <span class="tuck-caret" aria-hidden="true">▸</span>
      <span class="panel-cap notes-cap">on the breakdown · nondeterministic vs deterministic</span>
    </summary>
    <div class="panel-inner notes">
      <p class="note-lead">
        The instinct is correct, and it is the lab's spine: a belief is proposed by the
        nondeterministic and settled by the deterministic. Three sharpenings —
      </p>
      <ol class="note-list">
        <li>
          <span class="note-k">A flow, not two buckets.</span>
          Human, agent, LLM are all <em>SENSORS</em>; hash, test, chain, market are all
          <em>INSTRUMENTS</em> that settle. The same belief crosses from one role to the other. <span class="dim">(agents reason · substrate verifies)</span>
        </li>
        <li>
          <span class="note-k">A ladder, not a binary.</span>
          Between guess and settled sits <em>claimed</em> — cited, checkable, not yet SETTLED.
          Most knowledge lives on that middle rung; it is where the lab commits to what is worth
          the cost of settling.
        </li>
        <li>
          <span class="note-k">The real axis is reproducibility</span> — “can this be wrong
          without anyone noticing?” — not “human vs blockchain.” A chain is one deterministic
          substrate among many; a passing test or a recomputed hash is just as final.
        </li>
      </ol>
      <p class="note-tail">
        And the lab's own addition: every belief carries a <span class="note-k">cost × scope</span>.
        You do not settle everything — settling is expensive — you settle where the deterministic
        answer changes a decision. SETTLE-001 cost $0.075 and SETTLED a number two analytics firms
        sell.
      </p>
    </div>
  </details>
</main>

<style>
  main {
    max-width: 1180px;
    margin: 0 auto;
    padding: var(--space-1200) var(--space-600) var(--space-1200);
    position: relative;
    z-index: 1;
  }

  .head { margin-bottom: var(--space-800); }
  .kicker {
    color: var(--color-cyan-base);
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    letter-spacing: var(--tracking-whisper);
    text-transform: uppercase;
    margin: 0 0 var(--space-300);
  }
  h1 {
    color: var(--color-bone-bright);
    font-family: var(--font-mono);
    font-size: var(--text-2xl);
    letter-spacing: var(--tracking-emphasis);
    margin: 0 0 var(--space-300);
    font-weight: 500;
  }
  .thesis {
    color: var(--color-bone-dim);
    font-family: var(--font-mono);
    font-size: var(--text-sm);
    line-height: 1.6;
    max-width: 64ch;
    margin: 0;
  }
  .thesis em { color: var(--color-bone-base); font-style: normal; }

  /* ── panel shell (taste.md: bezel + inner surface, no radii) ── */
  .panel {
    background: linear-gradient(180deg, oklch(0.14 0.008 250) 0%, oklch(0.10 0.005 250) 100%);
    border: 1px solid var(--color-void-border);
    border-radius: 0;
    padding: var(--space-100);
    margin-bottom: var(--space-600);
  }
  .panel-inner {
    background: oklch(0.11 0.005 250);
    border: 1px solid oklch(0.22 0.012 250 / 0.6);
    border-radius: 0;
    padding: var(--space-600);
  }
  .panel-cap {
    color: var(--color-cyan-dim);
    font-family: var(--font-mono);
    font-size: var(--text-2xs);
    letter-spacing: var(--tracking-whisper);
    text-transform: uppercase;
    margin: 0 0 var(--space-100) var(--space-100);
  }

  /* ── the membrane ──
     Legibility (ALEXANDER spec): rung/verdict NAMES ride up the scale to the
     text-sm data floor; NOTES stay readable at text-xs (sub-annotation), never
     the text-2xs corner-telemetry register. Columns get room (wider gap, more
     vertical air per rung). Nothing structural below the data floor. */
  .membrane {
    display: grid;
    grid-template-columns: 1fr 0.92fr 1fr;
    gap: var(--space-800);
    align-items: stretch;
  }
  .field-label {
    font-family: var(--font-mono);
    font-size: var(--text-sm);
    letter-spacing: var(--tracking-terminal);
    margin: 0 0 var(--space-150);
  }
  .field-gen .field-label { color: var(--color-bone-dim); }
  .field-det .field-label { color: var(--color-phosphor-base); }
  .field-sub {
    color: var(--color-bone-ghost);
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    letter-spacing: var(--tracking-data);
    margin: 0 0 var(--space-400);
  }
  .chips { display: flex; flex-wrap: wrap; gap: var(--space-200); margin-bottom: var(--space-500); }
  .chip {
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    letter-spacing: var(--tracking-terminal);
    padding: var(--space-100) var(--space-300);
    border: 1px solid var(--color-void-border);
  }
  .chip-gen { color: var(--color-bone-base); border-color: var(--color-bone-ghost); }

  .ladder { display: flex; flex-direction: column; gap: var(--space-300); }
  .rung {
    display: flex; flex-direction: column; gap: var(--space-100);
    padding: var(--space-300) var(--space-400);
    border-left: 2px solid var(--color-void-border);
  }
  .rung-ghost { border-left-color: var(--color-bone-ghost); }
  .rung-dim   { border-left-color: var(--color-cyan-dim); }
  .rung-base  { border-left-color: var(--color-cyan-base); }
  .rung-name {
    font-family: var(--font-mono); font-size: var(--text-sm);
    letter-spacing: var(--tracking-terminal); color: var(--color-bone-base);
  }
  .rung-ghost .rung-name { color: var(--color-bone-muted); }
  .rung-note {
    font-family: var(--font-mono); font-size: var(--text-xs);
    line-height: var(--leading-normal);
    color: var(--color-bone-dim); letter-spacing: var(--tracking-data);
  }

  /* ── the gate (KANSEI / YANAGI motion build) ──
     Widened column + more vertical air; the cramped read is gone. The gate
     reads top-to-bottom: LABEL -> rule (same in -> same out) -> the CROSSING
     lane -> the four INSTRUMENTS -> never-an-LLM. Motion is STEPS ONLY. */
  .gate {
    position: relative;
    display: flex; flex-direction: column; align-items: center; text-align: center;
    gap: var(--space-400);
    padding: 0 var(--space-400);
    border-left: 1px solid var(--color-void-border);
    border-right: 1px solid var(--color-void-border);
  }

  /* THE LINE — the membrane, pulsing its glow on a slow steps(4) cycle.
     The checkpoint, breathing. Glow only (taste.md: no drop shadows). */
  .gate-line {
    position: absolute; top: 0; bottom: 0; left: 50%;
    width: 1px; background: var(--color-cyan-dim);
    opacity: 0.55;
    animation: membrane-pulse 1660ms steps(4) infinite;
  }
  @keyframes membrane-pulse {
    0%, 100% { box-shadow: 0 0 5px var(--color-cyan-dim); }
    50%      { box-shadow: 0 0 11px var(--color-cyan-base); }
  }

  .gate-label {
    color: var(--color-cyan-base); font-family: var(--font-mono);
    font-size: var(--text-sm); letter-spacing: var(--tracking-terminal);
    margin: 0; position: relative;
  }
  .gate-sub {
    color: var(--color-bone-dim); font-family: var(--font-mono);
    font-size: var(--text-xs); letter-spacing: var(--tracking-data);
    line-height: 1.5; margin: 0; position: relative;
  }

  /* THE CROSSING — a belief token steps the membrane left -> right in 8
     discrete jumps (steps(8) over 800ms = 8 perceptual cycles). It enters
     bone-ghost (proposed, unsettled) and lands phosphor at the right edge
     (the measured, SETTLED signal). The membrane is a checkpoint, not a
     slope: the token JUMPS, it never glides. */
  .crossing {
    position: relative;
    width: 100%;
    height: 16px;
    margin: var(--space-100) 0;
  }
  .crossing-rail {
    position: absolute; top: 50%; left: 0; right: 0;
    height: 1px; background: var(--color-void-border);
    transform: translateY(-50%);
  }
  .crossing-token {
    position: absolute; top: 50%; left: 0;
    width: 7px; height: 7px;
    transform: translate(0, -50%);
    background: var(--color-bone-ghost);
    animation: belief-cross var(--duration-deliberate) steps(8) infinite;
  }
  /* L->R traversal across the lane (lane width minus token width).
     At the far edge the token snaps to phosphor: the belief is SETTLED.
     keyframes interpolate left/background but steps(8) quantizes the path. */
  @keyframes belief-cross {
    0%   { left: 0;    background: var(--color-bone-ghost); }
    84%  {             background: var(--color-bone-dim); }
    100% { left: calc(100% - 7px); background: var(--color-phosphor-base); box-shadow: 0 0 6px var(--color-phosphor-glow); }
  }

  /* THE INSTRUMENTS — the four settlers boot line-by-line on entry
     (beam-draw raster, 83ms quantum stagger). The gate powers up. After the
     boot they rest static — instruments do not fidget. */
  .gate-instruments { display: flex; flex-direction: column; gap: var(--space-200); position: relative; width: 100%; }
  .instr {
    font-family: var(--font-mono); font-size: var(--text-sm);
    letter-spacing: var(--tracking-terminal); color: var(--color-cyan-dim);
    border: 1px solid var(--color-void-border); padding: var(--space-100) var(--space-200);
    background: var(--color-void-base);
    animation: instr-boot 166ms steps(4) backwards;
    animation-delay: calc(var(--instr-i) * 83ms);
  }
  @keyframes instr-boot {
    from { clip-path: inset(0 100% 0 0); }
    to   { clip-path: inset(0); }
  }

  .gate-rule {
    color: var(--color-anomaly-dim); font-family: var(--font-mono);
    font-size: var(--text-xs); letter-spacing: var(--tracking-emphasis);
    margin: 0; position: relative;
  }

  /* Respect reduced motion: no pulse, no traversal, no boot. The token rests
     SETTLED at the right edge (phosphor) — the meaning still reads statically. */
  @media (prefers-reduced-motion: reduce) {
    .gate-line { animation: none; box-shadow: 0 0 8px var(--color-cyan-base); }
    .instr { animation: none; }
    .crossing-token {
      animation: none;
      left: calc(100% - 7px);
      background: var(--color-phosphor-base);
      box-shadow: 0 0 6px var(--color-phosphor-glow);
    }
  }

  .verdicts { display: flex; flex-direction: column; gap: var(--space-300); }
  .verdict {
    display: flex; flex-direction: column; gap: var(--space-100);
    padding: var(--space-300) var(--space-400);
    border-left: 2px solid;
  }
  .v-name { font-family: var(--font-mono); font-size: var(--text-sm); letter-spacing: var(--tracking-terminal); }
  .v-note { font-family: var(--font-mono); font-size: var(--text-xs); line-height: var(--leading-normal); color: var(--color-bone-dim); }
  .v-held { border-left-color: var(--color-phosphor-base); }
  .v-held .v-name { color: var(--color-phosphor-base); text-shadow: 0 0 6px var(--color-phosphor-glow); }
  .v-falsified { border-left-color: var(--color-anomaly-base); }
  .v-falsified .v-name { color: var(--color-anomaly-base); text-shadow: 0 0 6px var(--color-anomaly-glow); }
  .v-insufficient { border-left-color: var(--color-bone-ghost); }
  .v-insufficient .v-name { color: var(--color-bone-muted); }

  /* ── worked example (hero · SETTLE-001) ──
     Bumped up the scale 2026-06-13 (feel-and-apply, operator: "a lot bigger
     fonts and clearer"). text-2xs is corner-telemetry ONLY (tokens.css:60);
     this is the page's hero, so nothing here renders below the text-sm data
     floor. Result number owns the panel at text-2xl, bone-bright (TDR-007). */
  .example {
    display: grid;
    grid-template-columns: 1fr 0.6fr 1fr;
    gap: var(--space-500);
    align-items: center;
  }
  .ex-tier {
    font-family: var(--font-mono); font-size: var(--text-base);
    letter-spacing: var(--tracking-terminal); margin: 0 0 var(--space-300);
    color: var(--color-bone-dim);
  }
  .ex-held { color: var(--color-phosphor-base); text-shadow: 0 0 6px var(--color-phosphor-glow); }
  .ex-belief {
    font-family: var(--font-mono); font-size: var(--text-lg); line-height: 1.45;
    color: var(--color-bone-base); margin: 0 0 var(--space-300);
  }
  .ex-result {
    color: var(--color-bone-bright); font-size: var(--text-2xl);
    line-height: 1.2; letter-spacing: var(--tracking-emphasis);
  }
  .ex-meta {
    font-family: var(--font-mono); font-size: var(--text-sm); line-height: 1.55;
    color: var(--color-bone-muted); margin: 0 0 var(--space-200);
  }
  .ex-source {
    font-family: var(--font-mono); font-size: var(--text-sm); line-height: 1.55;
    letter-spacing: var(--tracking-data); color: var(--color-bone-dim);
    margin: 0 0 var(--space-300);
  }
  .ex-stamp {
    font-family: var(--font-mono); font-size: var(--text-base);
    letter-spacing: var(--tracking-emphasis); color: var(--color-bone-dim);
    border-top: 1px solid var(--color-void-border); padding-top: var(--space-300); margin: 0;
  }
  .ex-held-stamp { color: var(--color-phosphor-dim); border-top-color: var(--color-phosphor-glow); }
  .ex-arrow { text-align: center; display: flex; flex-direction: column; align-items: center; gap: var(--space-200); }
  .ex-arrow-glyph {
    font-family: var(--font-mono); font-size: var(--text-2xl); color: var(--color-cyan-bright);
    text-shadow: 0 0 10px var(--color-cyan-base);
  }
  .ex-arrow-lbl {
    font-family: var(--font-mono); font-size: var(--text-sm); line-height: 1.5;
    letter-spacing: var(--tracking-terminal); color: var(--color-cyan-dim);
  }
  .ex-query {
    font-family: var(--font-mono); font-size: var(--text-sm); line-height: 1.5;
    letter-spacing: var(--tracking-data); color: var(--color-cyan-base);
    text-decoration: none; border-bottom: 1px solid var(--color-cyan-dim);
    transition: color var(--duration-fast) var(--ease-snap), border-bottom-color var(--duration-fast) var(--ease-snap);
  }
  .ex-query:hover {
    color: var(--color-cyan-bright); border-bottom-color: var(--color-cyan-bright);
    text-shadow: 0 0 8px var(--color-cyan-base);
  }
  .ex-arrow-cost {
    font-family: var(--font-mono); font-size: var(--text-sm); line-height: 1.5;
    letter-spacing: var(--tracking-data); color: var(--color-bone-muted);
  }

  /* ── refinement notes ── */
  .note-lead, .note-tail {
    font-family: var(--font-mono); font-size: var(--text-sm); line-height: 1.65;
    color: var(--color-bone-dim); margin: 0 0 var(--space-400); max-width: 76ch;
  }
  .note-list { margin: 0 0 var(--space-400); padding-left: var(--space-500); }
  .note-list li {
    font-family: var(--font-mono); font-size: var(--text-sm); line-height: 1.6;
    color: var(--color-bone-dim); margin-bottom: var(--space-300); max-width: 74ch;
  }
  .note-k { color: var(--color-bone-bright); }
  .note-list em { color: var(--color-cyan-base); font-style: normal; }
  .dim { color: var(--color-bone-ghost); }

  /* ── refinement notes — tucked (a second read) ──
     The whole panel is a <details>; the cap is the summary. Caret rotates
     via steps(1). No smooth easing (taste.md). */
  .notes-summary {
    list-style: none;
    cursor: pointer;
    display: flex;
    align-items: baseline;
    gap: var(--space-200);
    padding: var(--space-300) var(--space-400);
  }
  .notes-summary::-webkit-details-marker { display: none; }
  .tuck-caret {
    color: var(--color-cyan-dim);
    font-family: var(--font-mono);
    font-size: var(--text-base);
    transition: transform var(--duration-fast) var(--ease-snap);
  }
  .notes-panel[open] .tuck-caret { transform: rotate(90deg); }
  .notes-cap { margin: 0; }
  .notes-summary:hover .notes-cap { color: var(--color-cyan-base); }

  @media (max-width: 860px) {
    .membrane, .example { grid-template-columns: 1fr; gap: var(--space-500); }
    .gate { border-left: none; border-right: none; border-top: 1px solid var(--color-void-border); border-bottom: 1px solid var(--color-void-border); padding: var(--space-400) 0; }
    .gate-line { display: none; }
  }
</style>
