/**
 * generate-keys.ts
 *
 * Generates an ES256 keypair for E2E testing.
 * - Writes base64-encoded PKCS8 private key to tests/e2e/.env.e2e
 * - Outputs raw PEM (private + public) to stdout for test harness consumption
 *
 * Usage:
 *   npx tsx tests/e2e/generate-keys.ts
 */

import { generateKeyPair, exportPKCS8, exportSPKI } from "jose";
import * as fs from "node:fs";
import * as path from "node:path";

async function main(): Promise<void> {
  // Generate ES256 (P-256 ECDSA) keypair — extractable required for PKCS8/SPKI export
  const { publicKey, privateKey } = await generateKeyPair("ES256", { extractable: true });

  // Export keys as PEM strings
  const privatePem = await exportPKCS8(privateKey);
  const publicPem = await exportSPKI(publicKey);

  // Base64-encode the private PEM for injection via env var
  const privateBase64 = Buffer.from(privatePem, "utf-8").toString("base64");

  // Build .env.e2e content
  const envContent = [
    "# Auto-generated by generate-keys.ts — DO NOT COMMIT",
    `E2E_ES256_PRIVATE_KEY=${privateBase64}`,
    `FINN_S2S_PRIVATE_KEY=${privateBase64}`,
    "",
  ].join("\n");

  // Resolve paths relative to this script's location
  const e2eDir = import.meta.dirname ?? path.dirname(new URL(import.meta.url).pathname);
  const envPath = path.join(e2eDir, ".env.e2e");

  // Write .env.e2e
  fs.writeFileSync(envPath, envContent, { mode: 0o600 });
  console.log(`[generate-keys] Wrote ${envPath}`);

  // Ensure .env.e2e is in .gitignore (atomic read+append, no TOCTOU)
  const gitignorePath = path.resolve(e2eDir, "..", "..", ".gitignore");
  try {
    const gitignore = fs.readFileSync(gitignorePath, "utf-8");
    if (!gitignore.includes(".env.e2e")) {
      fs.appendFileSync(gitignorePath, "\n# E2E test keys (generated)\ntests/e2e/.env.e2e\n");
      console.log("[generate-keys] Added .env.e2e to .gitignore");
    }
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    // .gitignore doesn't exist — nothing to update
  }

  // Output PEM keys to stdout for test harness use
  console.log("\n--- ES256 PRIVATE KEY (PKCS8 PEM) ---");
  console.log(privatePem.trim());
  console.log("\n--- ES256 PUBLIC KEY (SPKI PEM) ---");
  console.log(publicPem.trim());
  console.log("\n--- BASE64-ENCODED PRIVATE KEY ---");
  console.log(privateBase64);
}

main().catch((err) => {
  console.error("[generate-keys] Fatal error:", err);
  process.exit(1);
});
