#!/usr/bin/env bats
# =============================================================================
# tests/unit/cycle-124-anthropic-catalog.bats
#
# cycle-124 Sprint 1 Task 1.3 (FR-3 / SDD §2.1) — the catalog's new
# generation is reachable end-to-end, and every generated twin of
# model-config.yaml is regenerated by ONE deterministic script:
#   - `opus` → claude-opus-5, `fable` → claude-fable-5-1 (cheval --dry-run)
#   - bare self-maps for the new ids resolve
#   - generated bash maps + BB config.generated.ts carry the new ids
#   - BB truncation budgets follow effective_input_ceiling − 20000 (SKP-003)
#   - dist/ twin of truncation.generated.ts is in step with the .ts
#   - tools/regen-model-artifacts.sh --check is green and a second run is
#     a no-op (idempotence)
#   - model-config.yaml.checksum matches the yaml
# =============================================================================

setup() {
    SCRIPT_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")" && pwd)"
    PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
    CHEVAL_PY="$PROJECT_ROOT/.claude/adapters/cheval.py"
    if [[ -x "$PROJECT_ROOT/.venv/bin/python" ]]; then
        PYTHON_BIN="$PROJECT_ROOT/.venv/bin/python"
    else
        PYTHON_BIN="$(command -v python3)"
    fi
    GENERATED_MAPS="$PROJECT_ROOT/.claude/scripts/generated-model-maps.sh"
    BB_DIR="$PROJECT_ROOT/.claude/skills/bridgebuilder-review"
    BB_CONFIG="$BB_DIR/resources/config.generated.ts"
    BB_TRUNC_TS="$BB_DIR/resources/core/truncation.generated.ts"
    BB_TRUNC_JS="$BB_DIR/dist/core/truncation.generated.js"
    REGEN="$PROJECT_ROOT/tools/regen-model-artifacts.sh"
    export LOA_MODELINV_LOG_PATH="$BATS_TEST_TMPDIR/modelinv.jsonl"
    export LOA_COST_LEDGER_PATH="$BATS_TEST_TMPDIR/cost-ledger.jsonl"
}

# Run cheval --dry-run for $1; assert anthropic + resolved_model == $2.
_assert_resolves() {
    local model="$1" expected="$2"
    run env -u ANTHROPIC_API_KEY "$PYTHON_BIN" "$CHEVAL_PY" \
        --agent reviewing-code \
        --model "$model" \
        --prompt "cycle-124-pin" \
        --dry-run \
        --json-errors 2>&1
    [ "$status" -eq 0 ] || {
        printf 'FAIL: cheval --dry-run rejected model=%s\n%s\n' "$model" "$output" >&2
        return 1
    }
    [[ "$output" == *"\"resolved_provider\": \"anthropic\""* ]] || {
        printf 'FAIL: model=%s did not resolve to anthropic\n%s\n' "$model" "$output" >&2
        return 1
    }
    [[ "$output" == *"\"resolved_model\": \"$expected\""* ]] || {
        printf 'FAIL: model=%s did not resolve to %s\n%s\n' "$model" "$expected" "$output" >&2
        return 1
    }
}

@test "c124-1.3-1: opus alias resolves to claude-opus-5" {
    _assert_resolves "opus" "claude-opus-5"
}

@test "c124-1.3-2: claude-opus-5 bare self-map resolves" {
    _assert_resolves "claude-opus-5" "claude-opus-5"
}

@test "c124-1.3-3: fable alias resolves to claude-fable-5-1" {
    _assert_resolves "fable" "claude-fable-5-1"
}

@test "c124-1.3-4: claude-fable-5-1 bare self-map resolves" {
    _assert_resolves "claude-fable-5-1" "claude-fable-5-1"
}

@test "c124-1.3-5: claude-opus-4-8 stays pinnable (cycle-114 self-map preserved)" {
    _assert_resolves "claude-opus-4-8" "claude-opus-4-8"
}

@test "c124-1.3-6: generated bash maps carry the new ids across provider/id/alias maps" {
    [ -f "$GENERATED_MAPS" ]
    grep -q '\["claude-opus-5"\]="anthropic"' "$GENERATED_MAPS"
    grep -q '\["claude-opus-5"\]="claude-opus-5"' "$GENERATED_MAPS"
    grep -q '\["opus"\]="claude-opus-5"' "$GENERATED_MAPS"
    grep -q '\["claude-fable-5-1"\]="anthropic"' "$GENERATED_MAPS"
    grep -q '\["fable"\]="claude-fable-5-1"' "$GENERATED_MAPS"
}

@test "c124-1.3-7: BB config.generated.ts carries claude-opus-5 and claude-fable-5-1" {
    [ -f "$BB_CONFIG" ]
    grep -q '"claude-opus-5"' "$BB_CONFIG"
    grep -q '"claude-fable-5-1"' "$BB_CONFIG"
}

@test "c124-1.3-8: BB truncation budgets derive maxInput from effective_input_ceiling − 20000" {
    [ -f "$BB_TRUNC_TS" ]
    # 180000 − 20000 = 160000 for every Anthropic HTTP entry; the codegen header says so.
    grep -q 'effective_input_ceiling' "$BB_TRUNC_TS"
    for m in claude-opus-5 claude-fable-5-1 claude-opus-4-8 claude-sonnet-5 claude-haiku-4-5-20251001; do
        grep -qE "\"$m\": \{ maxInput: 160000," "$BB_TRUNC_TS" || {
            printf 'FAIL: %s does not carry maxInput 160000\n' "$m" >&2
            grep "\"$m\"" "$BB_TRUNC_TS" >&2 || true
            return 1
        }
    done
    # Entries without a ceiling keep context_window (claude-headless has no ceiling; 1M mirrors its cli_model).
    grep -qE '"claude-headless": \{ maxInput: 1000000,' "$BB_TRUNC_TS"
}

@test "c124-1.3-9: dist/ twin of truncation.generated.ts carries identical maxInput values" {
    [ -f "$BB_TRUNC_JS" ] || skip "BB dist not built"
    local ts_budgets js_budgets
    ts_budgets="$(grep -oE '"[^"]+": \{ maxInput: [0-9]+' "$BB_TRUNC_TS" | sort)"
    js_budgets="$(grep -oE '"[^"]+": \{ maxInput: [0-9]+' "$BB_TRUNC_JS" | sort)"
    [ -n "$ts_budgets" ]
    [ "$ts_budgets" = "$js_budgets" ] || {
        diff <(echo "$ts_budgets") <(echo "$js_budgets") >&2 || true
        return 1
    }
}

@test "c124-1.3-10: model-config.yaml.checksum matches the yaml" {
    local recorded actual
    recorded="$(tr -d '[:space:]' < "$PROJECT_ROOT/.claude/defaults/model-config.yaml.checksum")"
    actual="$(sha256sum "$PROJECT_ROOT/.claude/defaults/model-config.yaml" | awk '{print $1}')"
    [ "$recorded" = "$actual" ]
}

@test "c124-1.3-11: tools/regen-model-artifacts.sh --check is green (all three drift gates + checksum)" {
    [ -x "$REGEN" ]
    command -v npm >/dev/null || skip "npm not available"
    [ -d "$BB_DIR/node_modules" ] || skip "bridgebuilder node_modules not installed (npm ci)"
    run bash "$REGEN" --check
    [ "$status" -eq 0 ] || { echo "$output" >&2; return 1; }
}

@test "c124-1.3-12: tools/regen-model-artifacts.sh is idempotent (second run changes nothing)" {
    [ -x "$REGEN" ]
    command -v npm >/dev/null || skip "npm not available"
    [ -d "$BB_DIR/node_modules" ] || skip "bridgebuilder node_modules not installed (npm ci)"
    # The dist manifest carries a `generated_at` stamp that changes on every
    # build; idempotence is about content, so fingerprint it without the stamp.
    _fingerprint() {
        sha256sum "$GENERATED_MAPS" "$BB_CONFIG" "$BB_TRUNC_TS" \
            "$PROJECT_ROOT/.claude/defaults/model-config.yaml.checksum" 2>/dev/null | awk '{print $1}'
        jq -S 'del(.generated_at)' "$BB_DIR/dist/.build-manifest.json" 2>/dev/null | sha256sum | awk '{print $1}'
    }
    local manifest="$BB_DIR/dist/.build-manifest.json" orig_manifest
    orig_manifest="$(cat "$manifest")"
    run bash "$REGEN"
    [ "$status" -eq 0 ] || { echo "$output" >&2; return 1; }
    local first second
    first="$(_fingerprint)"
    run bash "$REGEN"
    [ "$status" -eq 0 ] || { echo "$output" >&2; return 1; }
    second="$(_fingerprint)"
    [ "$first" = "$second" ]
    # Leave the tree as found: only the manifest's build stamp moved.
    if [ "$(jq -S 'del(.generated_at)' <<<"$orig_manifest")" = "$(jq -S 'del(.generated_at)' "$manifest")" ]; then
        printf '%s\n' "$orig_manifest" > "$manifest"
    fi
}

@test "c124-1.3-13: regen script rejects unknown arguments with exit 2" {
    [ -x "$REGEN" ]
    run bash "$REGEN" --bogus
    [ "$status" -eq 2 ]
}

@test "c124-1.3-14: a missing toolchain is exit 3 (TOOLCHAIN), never exit 1 (drift)" {
    [ -x "$REGEN" ]
    local bin="$BATS_TEST_TMPDIR/bin"
    mkdir -p "$bin"
    ln -s "$(command -v bash)" "$bin/bash"
    ln -s "$(command -v dirname)" "$bin/dirname"
    run env PATH="$bin" bash "$REGEN" --check
    [ "$status" -eq 3 ]
    [[ "$output" == *"TOOLCHAIN"* ]]
    [[ "$output" != *"DRIFT"* ]]
}
